#!/usr/bin/env bash
# Capture the sitl_drone changes to the ArduPilot tree as patch files.
#
# ArduPilot and its mavlink submodule are separate clones (PROJECT.md §3 Repo
# layout) and are NOT tracked by this repo. A `git submodule update` in
# ~/ardupilot discards uncommitted work in modules/mavlink without warning, so
# every ArduPilot-side change is mirrored here as a patch.
#
# Run after any edit to the ArduPilot tree. Apply with scripts/apply_patches.sh.
set -euo pipefail

AP="${AP:-$HOME/ardupilot}"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/patches"

emit() {  # emit <subdir-relative-to-AP or "."> <output name>
    local dir="$1" name="$2" path="$AP"
    [[ "$dir" != "." ]] && path="$AP/$dir"

    # --ignore-submodules: a dirty submodule shows up in the parent as a
    # "Subproject commit ...-dirty" hunk, which is noise, not a change.
    if ! git -C "$path" diff --ignore-submodules --quiet; then
        git -C "$path" diff --ignore-submodules > "$OUT/$name.patch"
        echo "wrote patches/$name.patch  ($(git -C "$path" diff --ignore-submodules --numstat | wc -l) file(s))"
    else
        rm -f "$OUT/$name.patch"
        echo "no changes in $dir — removed patches/$name.patch if present"
    fi
}

mkdir -p "$OUT"
emit modules/mavlink mavlink   # message definitions (ardupilotmega.xml)
emit .               ardupilot # ArduCopter / AP_Motors / GCS_MAVLink

# Record what the patches were made against, so they can be rebased knowingly.
{
    echo "# Generated by scripts/make_patches.sh — do not edit by hand."
    echo "ardupilot      $(git -C "$AP" rev-parse HEAD)"
    echo "modules/mavlink $(git -C "$AP/modules/mavlink" rev-parse HEAD)"
} > "$OUT/BASE"
echo "wrote patches/BASE"
